# -*- coding: utf-8 -*-
"""EBACProjeto01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w332023JN-5ypa-Oi2tvnugky9zWSdvI
"""

senha_permetida = 1808
senha_usuario = int(input('Digite sua senha: '))
while senha_usuario != senha_permetida:
    print('Senha incorreta. Tente novamente.')
    senha_usuario = int(input('Digite sua senha: '))
if senha_usuario == senha_permetida:
    print('Acesso permitido')
    print('Seja bem-vindo!')
    print('Vamos fazer diversas comparações com base em dois número!')
else:
    print('Acesso negado')

if senha_usuario == senha_permetida:
 num1 = float(input('Digite primeiro número: '))
 num2 = float(input('Digite segundo número: '))
print('Segue diversos resultados com base nos números', num1,'e',num2,':')
print('Adisão: ', num1 + num2)
print('Subtração: ',num1 - num2)
print('Multiplicação: ',num1 * num2)
print('Divisão: ',num1 / num2)
print('Potenciação: ',num1 ** num2)
print('Primeiro número é diferente do segundo? ',num1 != num2)
print('Primeiro número é igual ao segundo? ',num1 == num2)
print('Primeiro número é maior que o segundo? ',num1 > num2)
print('Primeiro número é menor que o segundo? ',num1 < num2)
print('Primeiro número é maior ou igual ao segundo? ',num1 >= num2)
print('Primeiro número é menor ou igual ao segundo? ',num1 <= num2)
print(num1 > num2 and num2 < num1)
print(num1 > num2 or num2 < num1)
print(not num1 > num2)
print(not num1 < num2)